### ISSUE TITLE
Miss ./datasets 

### ISSUE THREAD

**Issue by VCCIV** [hehefan/Point-Spatio-Temporal-Convolution#1]
hi, i find  "from datasets.msr import MSRAction3D" in train-msr.py.  Could you upload the folder ./datasets

**Comment by JohnsonSign** [comment]
hi, 
How can I get “ datasets.msr” for importing MSRAction3D.
thanks

**Comment by hehefan** [comment]
Hi both, 
Apologies for the omission. I just uploaded the code. Thank you.

Best,
