### ISSUE TITLE
Issue with running train-msr.py

### ISSUE THREAD

**Issue by Mrigankshi** [hehefan/Point-Spatio-Temporal-Convolution#12]
Hi @hehefan,
Thank you for your work and for making the PSTNet code available.
I am trying to reproduce the results on MSR 3d Action Data but running into "PSTConv: Temporal parameter error!".
I had to modify some parameters for conv2a  and conv3a layers of the MSR network to make it work, but that gives me ~70% accuracy in 35 epochs training.

Would you have any advice on what would be the correct way to fix the kernel dimensions? 

Thanks!

**Comment by hehefan** [comment]
Hi @Mrigankshi,

I fixed a bug in datasets/msr.py. Could you please try it again?

Best

**Comment by Mrigankshi** [comment]
Hi @hehefan 
Thank you so much for the fix! 
I was able to reproduce the results. Closing this issue!
