### ISSUE TITLE
about usage

### ISSUE THREAD

**Issue by amiltonwong** [hehefan/Point-Spatio-Temporal-Convolution#3]
Hi, @hehefan ,

Thanks for releasing the package. Would you also release a basic step-by-step guide for the usage of PSTConv? e.g, data preparation, training steps and prediction steps...

Thanks~

**Comment by hehefan** [comment]
Hi @amiltonwong ,

1. Data preparation. You can follow [MeteorNet](https://github.com/xingyul/meteornet) to generate the MSR-Action3D and Synthia 4D data. Here is my processed [MSR-Action3D](https://drive.google.com/file/d/1QWZA3OyhaOcQcCMF-Sz9thjRJRExICIz/view?usp=sharing) dataset.  For NTU RGB+D 60/120, please refer to [scripts](https://github.com/hehefan/Point-Spatio-Temporal-Convolution/tree/main/scripts).  
2. Training and prediction. Please run the [train-msr.py](https://github.com/hehefan/Point-Spatio-Temporal-Convolution/blob/main/train-msr.py) script. 

Best.
