### ISSUE TITLE
Training code of NTU RGB+D 60 and 120

### ISSUE THREAD

**Issue by liujiaheng** [hehefan/Point-Spatio-Temporal-Convolution#5]
Hi, this is a nice paper. Could you release the codes of (model, dataset, training process) on NTU RGB+D 60 and 120?

Thanks.

**Comment by hehefan** [comment]
Hi @liujiaheng,

Sorry for my late reply. I have just released the related codes. 

Best.

**Comment by liujiaheng** [comment]
Thanks for your code. Could you release the pre-trained  models of NTU60?

**Comment by hehefan** [comment]
Hi @liujiaheng,

Please find the  pre-trained NTU60 model via the link https://drive.google.com/file/d/1xHWs8dyLaNNPxhumCp-hWfMQN_DSepFn/view?usp=sharing

Best.

**Comment by sheshap** [comment]
NTU 60 for subject is working. 

Can you please share for NTU120 and both subject and view?

Thanks in advance
