### ISSUE TITLE
Dataloader for NTU RGB+D 60

### ISSUE THREAD

**Issue by JinyangGuo** [hehefan/Point-Spatio-Temporal-Convolution#6]
Hi there,

Thanks for your interesting work. Can you provide the dataset file for the NTU RGBD 60 cross view setting?

Regards,
Jinyang

**Comment by hehefan** [comment]
Dear @JinyangGuo ,

Many apologies for my late reply. The settings are basically following the 3DV work. I may upload the related codes to the [PointNet2](https://github.com/hehefan/PSTNet2) repo.

Best regards.
