### ISSUE TITLE
Request for the MSR data set in npy format

### ISSUE THREAD

**Issue by Delusionx1** [hehefan/Point-Spatio-Temporal-Convolution#7]
Hi Hehe,

Can you pleaase share the npy data file for the MSR data set.
It is a bit struggle for me to phrase bin data into npy. 
Hope you can help me.

Best,
Xin

**Comment by hehefan** [comment]
Hi @Delusionx1,

Please find the  dataset from the link https://drive.google.com/file/d/1QWZA3OyhaOcQcCMF-Sz9thjRJRExICIz/view?usp=sharing

Best regards.
