### ISSUE TITLE
An Issue related to running the furthest_point_sampling function

### ISSUE THREAD

**Issue by NeilCui6** [hehefan/Point-Spatio-Temporal-Convolution#8]
Dear Author,

Hope you are well.

I got an issue related to the pointnet2_utils.py and setup.py files. When I stalled setup.py the file, I got a warning below related to the GCC version. 

<img width="770" alt="b2f965312567d709789efabf3f0db5d" src="https://user-images.githubusercontent.com/91051121/151651385-2e779cd7-839f-4b4f-967e-5ff80ebe45df.png">

Then when I was running the highlighted part within the setup.py below, I got an error of "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)".

![image](https://user-images.githubusercontent.com/91051121/151651566-e283ef05-1fb9-43e4-8fde-da7bc6f311d8.png)

Just wondering if you happen to know what's the issue? Does it related to the g++version?

Our PyTorch version is 1.2.0.

Many thanks! @hehefan

**Comment by hehefan** [comment]
Hi @NeilCui6, 

Did you successfully compile the PointNet++ operations?

**Comment by NeilCui6** [comment]
> Hi @NeilCui6,
> 
> Did you successfully compile the PointNet++ operations?

Many thanks for your reply, @hehefan ! All good now. It was the GCC version issue, which has been solved. 

May I ask you another question? when running the MSRAction dataset, do I need to do any conversion with the original bin type data(like using the codes provided by the dataset to load and display depth map )？ Also, do I need to convert it to cloud points like what needs to be done for the NTU data by using your depth2point4ntu.py code？

Thanks again!

**Comment by hehefan** [comment]
Hi, you do need to convert the MSRAction dataset. The MeteorNet work provides a way to do that.

**Comment by NeilCui6** [comment]
> 

All good now. Thanks a lot for your help! : ) @hehefan
